version = 1

[merge]
automerge_label = "ğŸ¤– Auto merge"
blocking_labels = ["âŒ Invalid"]
method = "squash"

[merge.message]
title = "pull_request_title"
body_type = "markdown"
body = "pull_request_body"
include_pr_number = true
include_pull_request_author = true
include_coauthors = true
include_pull_request_url = true
cut_body_after = '---'

[merge.automerge_dependecies]
versions = ["minor", "patch"]
usernames = ["dependabot"]